### ISSUE TITLE
Students exist in segmentation folders but not in audio folders nor excel sheets.

### ISSUE THREAD

**Issue by kwatcharasupat** [FBA-Janitor/MIG-FBA-Data-Cleaning#3]
| Year | Band | Student | Folder Path | Folder Content |
|-----|--------|-----------|-------------|-----------------|
| 2014 | middle | 46864 | /media/fba/MIG-FbaData/FBA2014/middleschool/assessments/46864 | ['46864_segment.txt', '46864_instrument.txt'] |
| 2014 | middle | 44822 | /media/fba/MIG-FbaData/FBA2014/middleschool/assessments/44822 | ['44822_segment.txt', '44822_instrument.txt'] |
| 2014 | middle | 44800 | /media/fba/MIG-FbaData/FBA2014/symphonicband/assessments/44800 | ['44800_segment.txt', '44800_instrument.txt'] |
| 2015 | symphonic | 57677 | TBA | 
| 2015 | symphonic | 53677 | TBA |
| 2017 | middle | 77122 | /media/fba/MIG-FbaData/FBA2017/middleschool/assessments/77122 | ['77122_segment.txt'] |
| 2018 | middle | 93401 | /media/fba/MIG-FbaData/FBA2018/middleschool/assessments/93401 | ['93401_segment.txt'] |

These students exist in segmentation folders but not in audio folders nor excel sheets. I am not sure how the segment files were even created without the audio files. The audio files are not misplaced either; they just don't exist in any audio folder.

cc: @alexanderlerch

**Comment by alexanderlerch** [comment]
Let's double check to make sure this is not a onedrive problem - there were some copy problems and I hope we haven't lost files.

**Comment by kwatcharasupat** [comment]
Related issue: #4 for misplaced files. I found more of similar issues in other years. I will do a full cross-check between audio, excels, and segmentation soon to check for any more unknown discrepancies.

"Mysterious" is for student IDs found in segmentation but not found in any excel sheets from any year or level. 

- 2014 concert: 2 mysterious IDs. 
- 2014 symphonic: 2 mysterious IDs. 
- 2015 symphonic: No mysterious IDs. 2 misplaced IDs, accounted for as being from 2015 middle (1) and 2015 concert (1).
- 2016 symphonic. 7 mysterious IDs. 542 misplaced IDs, accounted for as being from 2017 symphonic (541) and 2017 concert (1). This folder has essentially the same issues as 2017 symphonic and probably have identical content. The "actual" 2016 symphonic folder is missing.
- 2017 middle: 1 mysterious ID.
- 2017 symphonic: 7 mysterious IDs. 1 misplaced ID, accounted for as being from 2017 concert.
- 2017 middle: 1 mysterious ID.
- 2018 middle: 1 mysterious ID.

**Comment by kwatcharasupat** [comment]
Close to merge with #1
